import type { Metadata } from "next";
import {IBM_Plex_Mono} from "next/font/google";
import "./globals.css";
import SessionWrapper from "./components/SessionWrapper";
import Sidebar from "./components/Sidebar";

const IBM_Plex = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ['400', '700'],
  display: "swap",
  variable: '--font-plex',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`text-base-content`}>
        <SessionWrapper>
          <Sidebar />
          {children}
        </SessionWrapper>
      </body>
    </html>
  );
}
